gui:
  expandFocusedSidePanel: true
  nerdFontsVersion: "3"
  scrollHeight: 10
  shortTimeFormat: "2006-01-02 15:04:05"
  timeFormat: "2006-01-02 15:04:05"

git:
  allBranchesLogCmds:
    - git log --all --graph --color=always --pretty=format:'%C(green)%h%Creset -%C(#a6d189 bold)%d%Creset %s - %C(#8caaee)%cn%Creset %C(#e78284)(%cd)%Creset' --abbrev-commit --date=format:'%Y-%m-%d %H:%M:%S'
  branchLogCmd: "git log --graph --color=always --pretty=format:'%C(green)%h%Creset -%C(#a6d189 bold)%d%Creset %s - %C(#8caaee)%cn%Creset %C(#e78284)(%cd)%Creset' --abbrev-commit --date=format:'%Y-%m-%d %H:%M:%S' {{branchName}} --"
  log:
    showWholeGraph: false
  paging:
    colorArg: always
    pager: delta --dark --paging=never --side-by-side --line-numbers --file-style=omit --hunk-header-style="file line-number syntax" --true-color=always
