[build]
target = "x86_64-unknown-linux-musl"

[target.x86_64-unknown-linux-musl]
# rustflags = ["-C", "target-feature=+crt-static"]
# linker = "x86_64-linux-musl-g++"
linker = "x86_64-linux-musl-gcc"
