version: 7
profiles:
  - type: ssh
    name: 10.229.30.132 (kylin x86)
    icon: fas fa-desktop
    options:
      host: 10.229.30.132
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: f5d3936f-9a20-4abf-8ac7-4f0d7f41ba8a
    id: ssh:custom:10.229.30.132-(kylin-x86):ac14f1fb-487f-4a54-a3e2-5899673e1611
    disableDynamicTitle: true
  - type: ssh
    name: 10.229.30.66 (ubuntu x86)
    icon: fas fa-desktop
    options:
      host: 10.229.30.66
      algorithms: {}
      input: {}
    weight: -1
    group: f5d3936f-9a20-4abf-8ac7-4f0d7f41ba8a
    id: ssh:custom:10.229.30.66-(ubuntu-x86):39aca002-ca5c-491f-93de-72220bb21a0f
    disableDynamicTitle: true
  - type: ssh
    name: 10.229.30.82 (uos x86)
    icon: fas fa-desktop
    options:
      host: 10.229.30.82
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: f5d3936f-9a20-4abf-8ac7-4f0d7f41ba8a
    id: ssh:custom:10.229.30.82-(uos-x86):ebd05b1e-9ab7-4dc2-9d54-912a369cfadf
    disableDynamicTitle: true
  - type: ssh
    name: 10.46.153.36 (mac x86)
    icon: fas fa-desktop
    options:
      host: 10.46.153.36
      algorithms: {}
      input: {}
    weight: -1
    group: f5d3936f-9a20-4abf-8ac7-4f0d7f41ba8a
    id: ssh:custom:10.46.153.36-(mac-x86):47276973-6d2f-4d1f-b585-5d5b0e901d47
    disableDynamicTitle: true
  - type: ssh
    name: 10.46.155.21 (kylin arm)
    icon: fas fa-desktop
    options:
      host: 10.46.155.21
      algorithms: {}
      input: {}
    weight: -1
    group: f5d3936f-9a20-4abf-8ac7-4f0d7f41ba8a
    id: ssh:custom:10.46.155.21-(kylin-arm):635de395-20ba-4258-bb79-7e347c040b4b
    disableDynamicTitle: true
  - type: ssh
    name: 10.46.155.26 (uos arm)
    icon: fas fa-desktop
    options:
      host: 10.46.155.26
      algorithms: {}
      input: {}
    weight: -1
    group: f5d3936f-9a20-4abf-8ac7-4f0d7f41ba8a
    id: ssh:custom:10.46.155.26-(uos-arm):49d95bc6-c255-4e69-8c01-8c3782cb691a
    disableDynamicTitle: true
  - type: ssh
    name: 10.229.30.98 (5.4.0-192-generic)
    icon: fas fa-desktop
    options:
      host: 10.229.30.98
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      auth: password
      scripts: []
      forwardedPorts: []
    weight: -1
    id: >-
      ssh:custom:10.229.30.98-(5.4.0-192-generic):f9b28057-ab57-4804-9207-cd85cdc99e9d
    group: f96cf44c-a606-4c2e-883b-33cafb04beb6
    disableDynamicTitle: true
  - type: ssh
    name: 10.229.48.101 (uos 1050)
    icon: fas fa-desktop
    options:
      host: 10.229.48.101
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: f96cf44c-a606-4c2e-883b-33cafb04beb6
    id: ssh:custom:10.229.48.101-(uos-1050):f2772daf-486c-4475-9304-797148c1aa1a
    disableDynamicTitle: true
  - type: ssh
    name: 10.229.48.109 (5.4.0-204-generic)
    icon: fas fa-desktop
    options:
      host: 10.229.48.109
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: f96cf44c-a606-4c2e-883b-33cafb04beb6
    id: >-
      ssh:custom:10.229.48.109-(5.4.0-204-generic):f9270911-4dd5-4e87-a78c-7d7de315a499
    disableDynamicTitle: true
  - type: ssh
    name: 10.229.48.154 (kylin 2203 hwe)
    icon: fas fa-desktop
    options:
      host: 10.229.48.154
      algorithms:
        hmac:
          - hmac-sha1
          - hmac-sha1-etm@openssh.com
          - hmac-sha2-256
          - hmac-sha2-256-etm@openssh.com
          - hmac-sha2-512
          - hmac-sha2-512-etm@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group14-sha256
          - diffie-hellman-group16-sha512
          - ext-info-c
          - ext-info-s
          - kex-strict-c-v00@openssh.com
          - kex-strict-s-v00@openssh.com
        cipher:
          - aes128-ctr
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      input: {}
      privateKeys: []
      forwardedPorts: []
      scripts: []
    weight: -1
    group: f96cf44c-a606-4c2e-883b-33cafb04beb6
    id: >-
      ssh:custom:10.229.48.154-(kylin-2203-hwe):25b60298-d7eb-490b-899f-499e8d06edf0
    disableDynamicTitle: true
  - type: ssh
    icon: fas fa-desktop
    options:
      host: 10.229.48.89
      algorithms:
        cipher:
          - aes128-ctr
          - aes128-gcm
          - aes128-gcm@openssh.com
          - aes192-ctr
          - aes256-ctr
          - aes256-gcm
          - aes256-gcm@openssh.com
          - chacha20-poly1305@openssh.com
        kex:
          - curve25519-sha256
          - curve25519-sha256@libssh.org
          - diffie-hellman-group-exchange-sha256
          - diffie-hellman-group14-sha256
          - diffie-hellman-group15-sha512
          - diffie-hellman-group16-sha512
          - diffie-hellman-group17-sha512
          - diffie-hellman-group18-sha512
          - ecdh-sha2-nistp256
          - ecdh-sha2-nistp384
          - ecdh-sha2-nistp521
        serverHostKey:
          - ecdsa-sha2-nistp256
          - ecdsa-sha2-nistp384
          - ecdsa-sha2-nistp521
          - rsa-sha2-256
          - rsa-sha2-512
          - ssh-ed25519
          - ssh-rsa
      privateKeys:
        - file://C:\Users\10312567\.ssh\id_rsa
      auth: publicKey
      input: {}
    weight: -1
    name: 10.229.48.89 (uos 1032)
    id: ssh:custom:printer-copy:34abe360-605a-4692-beb2-0ebdecb465b0
    group: f96cf44c-a606-4c2e-883b-33cafb04beb6
    disableDynamicTitle: true
  - type: ssh
    name: 10.229.48.99 (kylin 2203)
    icon: fas fa-desktop
    options:
      host: 10.229.48.99
      algorithms: {}
      input: {}
    weight: -1
    group: f96cf44c-a606-4c2e-883b-33cafb04beb6
    id: ssh:custom:kylin-2203:cf4a251b-79ce-40dd-ad47-adbc91b0b439
    disableDynamicTitle: true
hotkeys:
  toggle-window: []
  copy:
    - Alt-C
  paste:
    - Alt-V
  home: []
  end: []
  previous-word: []
  next-word: []
  delete-previous-word: []
  delete-next-word: []
  clear: []
  zoom-in: []
  zoom-out: []
  reset-zoom: []
  ctrl-c: []
  copy-current-path: []
  search:
    - Ctrl-Shift-F
  pane-focus-all: []
  restart-telnet-session: []
  restart-ssh-session: []
  launch-winscp: []
  settings: []
  serial: []
  restart-serial-session: []
  new-window:
    - Alt-N
  new-tab:
    - - Alt-T
  profile-selector: []
  toggle-fullscreen:
    - - F11
  rename-tab: []
  close-tab:
    - Alt-W
  reopen-tab: []
  toggle-last-tab: []
  next-tab: []
  previous-tab: []
  move-tab-left: []
  move-tab-right: []
  rearrange-panes: []
  duplicate-tab: []
  tab-1:
    - Alt-1
  tab-2:
    - Alt-2
  tab-3:
    - Alt-3
  tab-4:
    - Alt-4
  tab-5:
    - Alt-5
  tab-6:
    - Alt-6
  tab-7:
    - Alt-7
  tab-8:
    - Alt-8
  tab-9:
    - Alt-9
  tab-10:
    - Alt-0
  tab-11: []
  tab-12: []
  tab-13: []
  tab-14: []
  tab-15: []
  tab-16: []
  tab-17: []
  tab-18: []
  tab-19: []
  tab-20: []
  split-right: []
  split-bottom: []
  split-left: []
  split-top: []
  pane-maximize: []
  pane-nav-up: []
  pane-nav-down: []
  pane-nav-left: []
  pane-nav-right: []
  pane-nav-previous: []
  pane-nav-next: []
  switch-profile: []
  close-pane: []
  profile: {}
  profile-selectors: {}
  select-all: []
  delete-line: []
  settings-tab: {}
  explode-tab: []
  combine-tabs: []
  pane-nav-1: []
  pane-nav-2: []
  pane-nav-3: []
  pane-nav-4: []
  pane-nav-5: []
  pane-nav-6: []
  pane-nav-7: []
  pane-nav-8: []
  pane-nav-9: []
  pane-increase-vertical: []
  pane-decrease-vertical: []
  pane-increase-horizontal: []
  pane-decrease-horizontal: []
  focus-all-tabs: []
  scroll-to-top:
    - Ctrl-PageUp
  scroll-up:
    - PageUp
  scroll-down:
    - PageDown
  restart-tab: []
  reconnect-tab: []
  command-selector:
    - Ctrl-Shift-P
  disconnect-tab: []
  group-selectors: {}
  scroll-to-bottom:
    - Ctrl-PageDown
terminal:
  searchOptions: {}
  colorScheme:
    name: Tomorrow Night
    foreground: '#c5c8c6'
    background: '#1d1f21'
    cursor: '#c5c8c6'
    colors:
      - '#000000'
      - '#cc6666'
      - '#b5bd68'
      - '#f0c674'
      - '#81a2be'
      - '#b294bb'
      - '#8abeb7'
      - '#ffffff'
      - '#000000'
      - '#cc6666'
      - '#b5bd68'
      - '#f0c674'
      - '#81a2be'
      - '#b294bb'
      - '#8abeb7'
      - '#ffffff'
  rightClick: menu
  copyOnSelect: false
  warnOnMultilinePaste: false
  bracketedPaste: false
  customColorSchemes: []
  profile: local:git-bash
  font: IntoneMono NFM
  useConPTY: false
  frontend: xterm
  lightColorScheme:
    name: Tabby Default Light
    foreground: '#4d4d4c'
    background: '#ffffff'
    cursor: '#4d4d4c'
    colors:
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
      - '#000000'
      - '#c82829'
      - '#718c00'
      - '#eab700'
      - '#4271ae'
      - '#8959a8'
      - '#3e999f'
      - '#ffffff'
  fontSize: 15
  sixel: false
  fontWeight: 360
ssh:
  knownHosts:
    - host: 10.229.30.33
      port: 22
      type: ecdsa-sha2-nistp256
      digest: VcEInhkmKlteMOJHRizKD0TVzLxq6F1I2aFeYcWlBAc=
    - host: 10.229.48.89
      port: 22
      type: ecdsa-sha2-nistp256
      digest: nCVdFSHqnrLyhijg2A/VHQGI4i76f4zG61kQ5FLbJLc=
    - host: 10.229.48.90
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 1oFBLSFsiw8iL6KBu648k6EXs3wwYTwrDeh1Ones/ds=
    - host: 10.229.48.91
      port: 22
      type: ecdsa-sha2-nistp256
      digest: STE2kQAmknWauR4s/AA5vl1HHWJQRziCH1dteISzfQs=
    - host: 10.229.48.115
      port: 22
      type: ecdsa-sha2-nistp256
      digest: oVx1N7AyaeAUIKAl9VGeYNK/7/lGMPMAjTBuoAqYm8I=
    - host: 10.229.30.99
      port: 22
      type: ecdsa-sha2-nistp256
      digest: SlcoDX2kseiR6bd/n0IO5Z6dzUsYlkCxt8Fx1EMPseU=
    - host: 10.229.48.100
      port: 22
      type: ecdsa-sha2-nistp256
      digest: c9zZlD1JafblVzqhNEpl+hkqMx00F2xm56dPXTltNFA=
    - host: 10.229.30.98
      port: 22
      type: ecdsa-sha2-nistp256
      digest: Yd0Lr6vfiA4A2pHKUczXzQTWjOTzVzsctU8PawdzvL8=
    - host: 10.229.30.132
      port: 22
      type: ecdsa-sha2-nistp256
      digest: j2UvizIdvLd0GQEQDhLzf7JiluvmLLW5bn8sGqb03DU=
    - host: 10.229.30.66
      port: 22
      type: ecdsa-sha2-nistp256
      digest: jUJT7+ZgcUkdqnx9nY08FbdzBRKLYf2XCPp6Lgzkm7w=
    - host: 10.229.30.82
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 7vloZmcCMMRak8gwHIWYtjsGquINn6/N3CHWP/PS1Us=
    - host: 10.229.48.101
      port: 22
      type: ecdsa-sha2-nistp256
      digest: nCVdFSHqnrLyhijg2A/VHQGI4i76f4zG61kQ5FLbJLc=
    - host: 10.229.48.154
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 1yy3K1tXwtnJt1gNnXatEvTZJR72O/gBoW0cgaCBUiA=
    - host: 10.229.48.109
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 6wxM0V37fKnBPFTZLcU897CC3n/tNrmHzqJN9MR6T+4=
    - host: 10.229.48.99
      port: 22
      type: ecdsa-sha2-nistp256
      digest: 2FkiysqqIGynMuu0I0hryLynddfgZnWGe5EXyyq08YA=
configSync:
  parts: {}
clickableLinks:
  modifier: ctrlKey
appearance: {}
hacks:
  disableGPU: true
  disableVibrancyWhileDragging: true
  enableFluentBackground: true
enableAnalytics: false
enableWelcomeTab: false
pluginBlacklist:
  - serial
  - linkifier
  - telnet
profileDefaults: {}
recoverTabs: false
electronFlags:
  - - force_discrete_gpu
    - '0'
accessibility:
  animations: false
providerBlacklist: []
commandBlacklist: []
groups:
  - id: f5d3936f-9a20-4abf-8ac7-4f0d7f41ba8a
    name: compile
  - id: f96cf44c-a606-4c2e-883b-33cafb04beb6
    name: develop
profileBlacklist: []
enableAutomaticUpdates: false
